server.port=5000
spring.data.mongodb.uri=mongodb://localhost:27017/adaptive-learning
jwt.secret=fallback_secret_key_which_should_be_long_enough_for_hmac_sha256
jwt.expiration=86400000
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=support@skillforge.com
spring.mail.password=password123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
